name: dooit-cicd

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python Environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Run migrations and collect static files
      run: |
        source env/bin/activate
        python manage.py makemigrations
        python manage.py migrate
        python manage.py collectstatic --no-input

    - name: Start Django server (background)
      run: |
        source env/bin/activate
        python manage.py runserver 8000 &
      continue-on-error: true

  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Set up Python Environment
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: '3.9'

  #     - name: Install Dependencies
  #       run: |
  #         python -m venv env
  #         source env/bin/activate
  #         pip install -r requirements.txt
  #         pip install coverage

  #     - name: Run Tests
  #       run: |
  #         source env/bin/activate
  #         echo "Starting tests"
  #         coverage erase
  #         coverage run --include="./*/*" --omit="./env/*,./project/*,./manage.py" manage.py test .
  #         coverage xml -i
  #         coverage report -m

  #     - name: Upload coverage report
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: coverage-report
  #         path: coverage.xml